style: github
template: CHANGELOG.md.tpl
info:
  title: CHANGELOG
  repository_url: https://github.com/jsporna/terraform-aws-selenium-grid
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
